# 开发环境配置
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/video_db
    username: postgres
    password: zhx1314

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    restart:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379



server:
  port: 8080

logging:
  level:
    root: INFO
    org.example.video_ai: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 开发环境 JWT 密钥（简单密钥，仅用于开发）
jwt:
  secret: dev-secret-key-change-in-production
  expiration: 86400000
